# Generated by Django 3.0.5 on 2020-05-02 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=False, verbose_name='Was the student present in the class?')),
            ],
            options={
                'verbose_name_plural': 'attendance',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HealthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'health groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SportClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date and time of the sport class')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=5400), verbose_name='Duration of the class')),
            ],
            options={
                'verbose_name_plural': 'sport classes',
                'ordering': ['date', 'group'],
            },
        ),
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('max_student_number', models.PositiveSmallIntegerField(default=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date group was created')),
            ],
            options={
                'verbose_name_plural': 'sport groups',
                'ordering': ['id'],
            },
        ),
    ]
