# Generated by Django 3.0.5 on 2020-05-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200501_2147'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentProfile',
        ),
        migrations.RenameModel(
            old_name='Trainer',
            new_name='TrainerProfile',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='trainer status'),
        ),
    ]
